### ISSUE TITLE
Lime collections not created in eXist ?

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#11]
I ran npm install for aknservices. 
But when I checked in eXist there are no lime2 specific folders created , this is the config in `aknservices/config.json` : 

```
"existIsMainBackend": true,
"existdb": {
    "host": "localhost",
    "port": 8080,
    "rest": "/exist/rest",
    "baseCollection": "/lime2_dev",
    "auth": "admin:admin"
},
```

lime2_dev is a colleciton inside the root collection of eXist . Even after i run `node server.js` the lime specific collectoins are absent in eXist.

**Comment by kohsah** [comment]
Basically the default installation points to sinatra.cirsfid.unibo.it as the back-end server. I want to switch it to my locally installed server running on port 9006, thats why I am trying the above.

**Comment by kohsah** [comment]
This is config.json from Lime client : 

```
1 {
  2     "languages": [{"name":"akoma3.0"}],
  3     "fieldsDefaults": {
  4         "docLocale": "it"
  5     },
  6     "server": {
  7         "node": "http://localhost:9006",
  8         "php": "php/"
  9     }
 10 }
~         
```

**Comment by kohsah** [comment]
Basically when I do the above, it doesnt allow me to log in to LIME since there are no users. I recall in Lime-1 the user directory was getting created and populated with default users. 

If I set node to : "http://sinatra.cirsfid.unibo.it/node/aknservices" the login works fine because its using your hosted backend. 

So something didnt get setup on the eXist side ?

**Comment by obujor** [comment]
In LIME 2 users are stored in MongoDB collection instead of eXist collection. 
`"existIsMainBackend": true` this configuration is for using eXist for storing documents not users.
In order to run the server locally you need to have a running MongoDB instance as listed in the [lime-server installation guide](https://github.com/cirsfid-unibo/lime-server/blob/master/Installation.md). 
If you already installed and configured an instance of MongoDB you need to create at least one user by clicking on the "Register" link in the login dialog shown below.
![lime - registration](https://cloud.githubusercontent.com/assets/3893568/13314673/a350dcb6-dba6-11e5-87b6-525710730411.jpeg)

**Comment by kohsah** [comment]
Great ... that sorted me out. Just needed to register a user.
