### ISSUE TITLE
languagePlugins and metadata Editors -- recommended usage ? 

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#12]
What is the recommended usage for implementing custom AN doc-types  ? 

1) I want to add a customized AN doc implementation ..  I have forked this project, so I just modify the default AN implementation in languagePlugins .... is that the recommended approach ? 

2) I also need to extend or add metadata editing screens which will pull information from an external data source. This doesnt seem to be within languagePlugins could you point me to the right place ?

**Comment by obujor** [comment]
It depends on what kind of customization you want to implement.

1) You can modify the existing language plugin or create a new one starting from the existing, it dipends on how much you need to change, so you can choose what is the best option in your case. [Here](http://lime.cirsfid.unibo.it/?page_id=33) you can find some documentation about languagePlugins, it's a little bit outdated but it's still a good starting point.

2) We're using [ExtJS 5](https://docs.sencha.com/extjs/5.1/) so for extending LIME you have to know how to use it and how to build ExtJS components. In order to exdent the interface or behaviour you need to create a new [Sencha Cmd package](https://docs.sencha.com/cmd/5.x/cmd_packages/cmd_packages.html) which extends or overrides one or more classes from existing packages, "akn-metadata" is the package which implements metadata editor. After creating the package you need to include it in "app.json" and refresh or compile the app.

**Comment by kohsah** [comment]
Thanks @obujor
