### ISSUE TITLE
Metadata editor for class attribute ? 

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#13]
I am trying to associate a class attribute value to a `<p>` marked up within a `<preface>`.

How do i enable an editor to add that attribute for the '<p>' element ?

**Comment by obujor** [comment]
You can add a widget in the "elements" object of  "_markupMenu_rules.json_" file found in the "default" folder or in any other docType folder e.g "doc", you can read more about widgets [here](http://lime.cirsfid.unibo.it/?page_id=33#!elements-object). 

Example of "class" widget:

``` json
"p": {
    "askFor": {
        "class": {
            "label": "class",
            "type": "text",
             "insert": {
                "attribute": {
                    "name": "class"
                }
            }
        }
    }
}
```

In order to see the widget you need to click on "p" element in LIME and in the widget should open (after saving the edited json file and reload LIME in the browser). 
This approach adds the "class" widget to all "p" not only within a "preface", but this is the easy way.

Otherwise you can create a new custom element with the "class" widget and put it only in the "preface", but in this way you need to change the "HtmlToAkn.xsl" file and mapping the custom element to a `<p>`.

**Comment by kohsah** [comment]
Great, that looks very cool --  thanks for the detailed explanation, I will try it out
