### ISSUE TITLE
Switching default locale ?

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#16]
How do I switch the default locale ? Currently the UI and defaults are always "it".

I changed docLocale to "en" in config.json but doesnt seem to have had any impact.

**Comment by obujor** [comment]
The document locale and the UI language are two different configurations. 
Currently in "fieldsDefaults" ("config.json" file) you only can specify the defaults of the documents created with LIME not for the UI. 
In "docLocale" field you can use one of the available locale specified in "structure.json" file of the used language e.g. "/languagesPlugins/akoma3.0/structure.json".

In order to change the default UI you need to change the "config.lang" field in "/packages/lime-core/src/Locale.js" file, and refresh or build LIME. 
You can also add "?lang=en" in the url to use English in the UI.

**Comment by kohsah** [comment]
Thanks @obujor that clears it up.
