### ISSUE TITLE
languagePlugins - two different kinds of debateReport

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#22]
I have two doc types which are both different kinds of debateReports (<debateReport name="REP" ... /> and <debateReport name="DC" ... /> ). I will eventually have a case where the base`<doc ...>` will have different sub-types and slightly different structures. 

Now in languagePlugins `structure.json` seems to map to the doctype element generated by the system. I need to call the doc types "dc-doc" and "rep" in structure.json. Right now it generates a doctype element as `<dc-doc .../>`. 

Which is the right place to customize this ... HtmltoAkn.xsl ?

**Comment by kohsah** [comment]
OK modifying HtmltoAkn.xsl worked for me. The one issue here is when I open the document again, it shows the document type as "debateReport" in the  "new document" drop-down (along with dc-doc )

**Comment by obujor** [comment]
HtmlToAkn.xsl is the right place to customize this things, but pay attention on how you change it, remember to change also AknToXhtml.xsl if in your case is needed. Be careful with customizing of those files because a lot of things depends of them. 
Make sure that your changes are compatible with AkomaNtoso document structure and metadata otherwise you need to change some of the "akn" packages, like "akn-main" and "akn-metadata".

**Comment by kohsah** [comment]
Thanks .. AknToHtml.xsl that stylesheet determines how the marked up elements are rendered in the Editor window ?

**Comment by obujor** [comment]
Yes, it transforms the Akn in the Editor processable internal format.
