### ISSUE TITLE
authorialNote unable to use

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#23]
The authorialNote does not appear to be usable. 

I have tried to insert a authorialNote in legitimate places, but it always throws up an error :

"Element authorialNote cannot be inserted here ! Pattern popup is not allowed in block/hcontainer/heading.." 

Also noticed that it is listed with pattern "popup" which I think was deprecated from AkomaNtoso, and also there is no implementation for pattern "popup" that I could find in the Lime code. Changing the pattern to `inline` didnt work either. 

Any suggestions on how to proceed here ?

**Comment by obujor** [comment]
Currently is working only the importing of the existing authorialNotes, their marking is not working very well, we'll fix it soon. 
But in general the autorialNotes can be inserted only in _inline_ elements, don't change the pattern to _inline_ because the _autorialNote_ can contain much more than _inline_ elements.

**Comment by kohsah** [comment]
Anyway I can help with the implementation, happy to. Just need pointing in the right direction. Yeah if I remember right, authorialNote follows the "flow" pattern in the schema.

**Comment by obujor** [comment]
Thank you for your availability to help in the implementation!
In this case the fix was only some tens of lines and I fixed this in [25a5306](https://github.com/cirsfid-unibo/lime/commit/25a530629d553e03232160c4e30a91faa956b1ad) and [fed633e](https://github.com/cirsfid-unibo/lime/commit/fed633e51ba1752d35e898cc93050450240d1794).
Now you can mark authorial notes in inline elements and by default they are moved to the bottom of the document, you can change the placement to inline or its marker in note widget that can be opened by clicking on the note.

**Comment by kohsah** [comment]
Great! thanks checking it out now .

**Comment by kohsah** [comment]
Works very nicely, just tested it.
