### ISSUE TITLE
Change marks - inline and block level

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#31]
Couple of questions on change marks. 

I have a scenario where a document gets modified. This can be at two levels : 

inline: there is insertion / deletion of a word/sentence, this is handled by content-inline - "set insertion" , "set deletion" -- no problem here. 

block level: one or more paragraphs (i.e. <p> within a <content> block )  may be added or deleted or a whole numbered paragragraph (e.g. <paragraph> with <num> ). How do I mark this up .. i.e. How do I markup a <paragraph> as inserted .i .e. Is there a "track changes" mode for LIME ?

**Comment by obujor** [comment]
In LIME there is not an automatic track chages.
In general it dipends on what kind of change mark you want to do. The content inline elements "set insertion" and "set deletion" are just text marks but don't add modification metadata, so there are not very userful without the metadata.

If you want to mark the modifications correctly including the metadata, you need to use buttons contained in "Active Modifications" and "Passive Modifications" depending on what kind of modification you want to mark. This buttons are added in the "Document Structure" by the "akn-mods-marker" package so ensure that this package is enabled in app.json file. 
Using the buttons inside the "Action" group you can mark inline modifications as well as block modifications, in order to mark a block as changed you need to click on the block (or on its label) and focus it without selecting text.

In LIME there are special modes for marking the modifications between two documents, which can be enabled from "Difference Viewer" (Window -> Show View) by clicking the "Edit" button in the middle after selecting the documents. This mode opens the two documents and it allows you to mark only the modifications, you can interact with the old version of the document for marking the modifications in the new version. This feature is implemented in "default-diff" (it should be called akn-diff, we'll change it) package so ensure that you have this package in app.json.

**Comment by kohsah** [comment]
Thanks @obujor . Do you happen to have a video of how to use the Active / Passive Modifications in LIME ?

**Comment by obujor** [comment]
Unfortunately currently we don't have any how to video.
