### ISSUE TITLE
Using an alternative PDF transformation service

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#33]
I want to integrate an existing REST service which takes a AN document as input and outputs a DOCX or PDF depending on which REST API has been called. This will be used instead of the existing PDF transformation functionality in LIME.

Any pointers where I should start looking ?

**Comment by kohsah** [comment]
Ok found the akn-fop-pdf package ... and there is the callPadf() function in Controller.js ... I guess that is the place.

**Comment by obujor** [comment]
Yes the "akn-fop-pdf" package is an alternative for "default-pdf". But this is using FOP for generating the pdf file. 
If you want to integrate another REST service you can create a new package similar to "default-pdf" or "akn-fop-pdf" and replace the default with it. 
Otherwise you can also create a package which overwrites the "default-pdf" with a custom "callPdfService" function, but in this case you need to include both packages in app.json.

**Comment by kohsah** [comment]
Thanks, thats pretty clear ... found the code too.
