### ISSUE TITLE
Missing data when Saving the document (during first autosave) 

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#45]
When I save the document for the first time, Some data entered on the new document form (e.g. I have added a field for inputting number, and specifying sub-type) , does not show up on the Save side model. 

If you look at HtmlSerializer.serialize when I console log model.getData() I get this : 

![image](https://cloud.githubusercontent.com/assets/5685392/15037327/a658b5b2-12b7-11e6-9778-c6f74ec35a01.png)

As you can see subtype and number are not set even though the information is available in DocumentProperties.documentInfo (from where country, type, and language are set). Right now I have simply set it from DocumentProperties.documentInfo directly ... but this seems wrong since they should be in the model. 

My question how do I get subtype and number into the model ?

**Comment by kohsah** [comment]
I think I found it : 

generateMetaXml() in akn-metadata.sync.ImportController 

Update: modified the template in generateMetaXml(), that seemed to fix the problem, had to convert it to an XTemplate since the subtype is conditional.

**Comment by obujor** [comment]
akn-metadata.sync.ImportController  is used for import the existing metadata from opened akn file or generate by calling generateMetaXml when the opened file is missing the metadata.

DocumentProperties.documentInfo and document metadata model are not connected, so you need to add the fields in the model store.
To get the document metadata store you need to call:
`Ext.getStore('metadata').getMainDocument();`
This returns the document store which is an instance of the document metadata model (AknMain.metadata.Document).

Actually in the editor the subtype and the number of document are added in the store when these elements are marked, this is done in AknMetadata.sync.EditorSynchronizer.

If you want to add these to the model on the creation or importing of a document you need to do in Akn-metadata.sync.ImportController.
In case of new document or importing a document without metadata (.doc or plain text) you need to add it like you said in the generateMetaXml() but also in importDocumentMeta() of the same file because this is the function that actually sets the fields into the metadata store by parsing the xml metadata. 
You can look for example at the line 118:
`store.set('type', akn.query('local-name(..)'));`
this sets the 'type' of the document in the store.

Remember that as it works now the subtype and the number are added in the AknMetadata.sync.EditorSynchronizer and in your case maybe you don't want to overwrite the initial values when the document is marked, it depends of the scenario that you have.

**Comment by kohsah** [comment]
Great, thanks @obujor  I didnt mention, but I did modify importDocumentMeta() too so I guess I am on the right track. Your explanation clarifies many things.
