### ISSUE TITLE
Unable to login to LIME with either demo account or new account

### ISSUE THREAD

**Issue by bourkedo** [cirsfid-unibo/lime#46]
I have run into a difficulty both when I have installed LIME in linux and also on Windows 10.
 
I believe I have all the pre-requisites installed and eXist and Mongo are running ok.  I can get to the logon screen for LIME but I cannot get it to accept the demo password or to allow me to Register a new user;
 
For Demo ie checkbox checked I get;

"Login Failed. Wrong username or password"
  
When I try to register a new user I get;
 
 "Registration failed. User already exists on the database."
 
Even though there are no users created in database

Any help that you can provide would be great.

**Comment by obujor** [comment]
This is a strange behavior, we have to investigate a little bit.
First error: demo credentials cannot be wrong, so I can deduce that the demo user is not present in the database, it is created on lime-server starts up.
Second error: if your database is empty the user cannot already be in the database, so this error message is inappropriate, probably LIME cannot comunicate with lime-server a proper error message reporting that is missing, we will add it soon.

I think the problem is that the lime-server is not running or that the port is wrong, could you check?

Here is the [installation guide](http://lime.cirsfid.unibo.it/?page_id=134) it could be that you missed the server part (in the build folder it can be called "aknservices" or "lime-server" depending on what release you downloaded).

**Comment by bourkedo** [comment]
Thanks for the reply.

You were correct, the lime server was not installed properly.  Despite some challenges I got it installed. 

Those challenges were;

The Installed version of Python was 3.4 which is an unsupported version, only 2.0 - 3.0 are supported, installed  2.7 and added the --python=C:\Python27 parameter to the npm install command.

A Microsoft Visual Studio C++ compiler was not installed, Installed Visual Studio 2017 and found that this later version was also unsupported, uninstalled it and installed VS 2015.

Re ran: npm install --Python=C:\Python27 and installation completed successfully without errors.

LIME editor opened and it was possible to log in with the demo account.
