### ISSUE TITLE
Importing docx files with header(s) fails

### ISSUE THREAD

**Issue by eltorre** [cirsfid-unibo/lime#72]
When importing an docx file that has a header, only the header content (the contents of word/header1.xml) gets into the editor.

A couple of related notes; I will open new issues if you see fit:
* Can LIME be adapted to work with Libreoffice ```soffice --headless --convert-to ...```? I found that Abiword:
  * Is no longer mantained (?). Last release is 3.0.2 from October 2016. 
  * Requires a massive amount of cruft. I need to install GTK+3 (with all the dependencies) just to use Abiword in headless mode. This is 600mb+ of useless dependencies that will be used by no other app in the server. Not only that, but the abiword apt-get package is broken, and does not include all the required dependencies when installing (namely, GTK+3).

* Can Lime implement a xml import mode? I found that copying and pasting akoma ntoso xml (the one shown in the Akoma Ntoso view in Lime) into the editor, saving and reloading properly renders the file. I assume that this is unintended behaviour and prone to errors, but it would be a nice as a supported feature.

**Comment by obujor** [comment]
Could you please attach a sample document containing headers?

- Yes, we are aware of these issues with Abiword, we are using Libreoffice in some instances but not yet replaced in the core because even libreoffice has some issues, we will see.
- LIME can do this, you can try by following these steps:
     - save your content as Xml File->Export as-> Xml
     - import the file you saved before File->Import document
If you are importing an Akomantoso xml file and it says that this is not supported this means that the MIME type of the file is not "application/xml" I think this can depend on your OS. You can see [here](https://github.com/cirsfid-unibo/lime-server/blob/master/documentsdb/services/FileToHtml.js#L66) the list of supported MIME types.

**Comment by eltorre** [comment]
Attached you may find a minimal file that triggers this behaviour.

[headertext.docx](https://github.com/cirsfid-unibo/lime/files/2115051/headertext.docx)

Created with Word 2013 15.0.5015.1000 MSO 1.5.0.4719.1000 32-bit

**Comment by obujor** [comment]
I tested this file in our environment, and it's working, your problem probably is the version of Abiword, we are using Abiword 2.8.2. Newer versions of Abiword are not yet supported, you can follow [this issue](https://github.com/cirsfid-unibo/lime-server/issues/6).

**Comment by eltorre** [comment]
Do you know of any reliable PPA with Abiword 2.8.2? I am having a lot of trouble finding it.

**Comment by obujor** [comment]
I don't, but you can try by downloading the package from [here](http://ppa.launchpad.net/abiword-stable/ppa/ubuntu/pool/main/a/abiword/) or compile it from the source or fix abiword 3 by changing [this](https://github.com/cirsfid-unibo/lime-server/blob/master/documentsdb/xslt/CleanConvertedHtml.xsl) file. I think the later is the easiest one, this xsl transformation is used to remove out almost all tags from the Abiword output.
